#
# Copyright (C) 2018 The TwrpBuilder Open-Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

LOCAL_PATH := device/lenovo/zippo


# Platform
TARGET_BOARD_PLATFORM := msmnile
TARGET_BOARD_PLATFORM_GPU := qcom-adreno640
QCOM_BOARD_PLATFORMS += sm8150


# Avb
BOARD_AVB_ENABLE := true
#BOARD_AVB_RECOVERY_KEY_PATH := external/avb/test/data/testkey_rsa4096.pem
#BOARD_AVB_RECOVERY_ALGORITHM := SHA256_RSA4096
#BOARD_AVB_RECOVERY_ROLLBACK_INDEX := 1
#BOARD_AVB_RECOVERY_ROLLBACK_INDEX_LOCATION := 1
#BOARD_AVB_ROLLBACK_INDEX := $(PLATFORM_SECURITY_PATCH_TIMESTAMP)
BOARD_OS_PATCH_LEVEL := 2019-06
BOARD_OS_VERSION := 9.0.0
#BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flag 2

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := msmnile
TARGET_NO_BOOTLOADER := true
TARGET_USES_UEFI := true

# System as root
BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
#BOARD_USES_RECOVERY_AS_BOOT := true
BOARD_ROOT_EXTRA_FOLDERS := bluetooth dsp firmware persist
BOARD_SUPPRESS_SECURE_ERASE := true


# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-2a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a76

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_CPU_VARIANT_RUNTIME := cortex-a76

TARGET_USES_64_BIT_BINDER := true

ENABLE_CPUSETS := true
ENABLE_SCHEDBOOST := true

# QCOM
#TARGET_USE_SDCLANG := true


# Partitions
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 5368709120
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_PARTITION_SIZE := 117413195776
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_PARTITION_SIZE := 1073741824
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_USES_MKE2FS := true
BOARD_ROOT_EXTRA_SYMLINKS := \
    /mnt/vendor/persist:/persist \
    /vendor/bt_firmware:/bt_firmware \
    /vendor/dsp:/dsp \
    /vendor/firmware_mnt:/firmware 
    

# File systems
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
TARGET_USES_MKE2FS := true

# Crypto
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := true
TW_INCLUDE_FBE_METADATA_DECRYPT := true
BOARD_USES_METADATA_PARTITION := true
#TARGET_HW_DISK_ENCRYPTION := true

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
#BOARD_HAS_NO_REAL_SDCARD := true
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_SUPPRESS_SECURE_ERASE := true
BOARD_USES_MMCUTILS := true
BOARD_SUPPRESS_EMMC_WIPE := true
include $(LOCAL_PATH)/kernel.mk


TARGET_OTA_ASSERT_DEVICE := zippo

# TWRP specific build flags
TW_THEME := portrait_hdpi
#RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_QCOM_RTC_FIX := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
#TW_EXTRA_LANGUAGES := true
#TW_INCLUDE_NTFS_3G := true
#TW_USE_TOOLBOX := true
TW_EXCLUDE_SUPERSU := true
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_BRIGHTNESS_PATH := "/sys/class/backlight/panel0-backlight/brightness"
TW_DEFAULT_BRIGHTNESS := 200
TW_NO_USB_STORAGE := true
#TW_EXCLUDE_MTP := true
#TW_EXCLUDE_ENCRYPTED_BACKUPS := true
#TW_NO_EXFAT := true
TWRP_INCLUDE_LOGCAT := true
#HAVE_SELINUX := true

TARGET_USES_LOGD := true
TW_HAS_EDL_MODE := true
#TW_DEFAULT_LANGUAGE := ru

# Hack: prevent anti rollback
PLATFORM_SECURITY_PATCH := 2099-06-01
PLATFORM_VERSION := 99.0.0
TARGET_COPY_OUT_VENDOR := vendor
#TARGET_RECOVERY_INITRC :=$(LOCAL_PATH)/recovery/root/init.rc
TW_USE_NEW_MINADBD := true
#TW_CRYPTO_USE_SYSTEM_VOLD := qseecomd hwservicemanager keymaster-4-0
#TARGET_KEYMASTER_WAIT_FOR_QSEE := true

TW_DEVICE_VERSION := compiled by alexeei
#TW_ROUND_SCREEN := true
#TW_NO_SCREEN_BLANK := true
TW_EXCLUDE_TWRPAPP := true
TW_Y_OFFSET := 80
TW_H_OFFSET := -80

# QSEECOMD DEPENDENCIES
TARGET_RECOVERY_DEVICE_MODULES      += libxml2.so
TW_RECOVERY_ADDITIONAL_RELINK_FILES += $(PRODUCT_OUT)/system/lib64/libxml2.so

TARGET_RECOVERY_DEVICE_MODULES      += libicuuc.so
TW_RECOVERY_ADDITIONAL_RELINK_FILES += $(PRODUCT_OUT)/system/lib64/libicuuc.so

# KEYMASTER DEPENDENCIES
TARGET_RECOVERY_DEVICE_MODULES      += libion.so
TW_RECOVERY_ADDITIONAL_RELINK_FILES += $(PRODUCT_OUT)/system/lib64/libion.so

TARGET_RECOVERY_DEVICE_MODULES      += android.hardware.weaver@1.0
TW_RECOVERY_ADDITIONAL_RELINK_FILES += $(PRODUCT_OUT)/system/lib64/android.hardware.weaver@1.0.so
